#!/usr/bin/env python3
"""Single-card industry pain statics: one card, one pain, one industry, one lead magnet.

Settled with you . This retires the 22 general-pain noir carousels as the live
set. Those were pain-generic with no industry and a generic quiz CTA; these are the same
canonical F5 look reduced to ONE card, targeted at a named industry and closing on that
industry's own lead magnet.

The shape:
  - **5 industries**, the top five in `context/pain-wiki/INDEX.md` by call volume. The same
    five `projects/content-engine/ideas/industry-build-carousels/VERTICALS.md` already maps.
  - **5 pains each**, the top five ranked pains in that industry's playbook at
    `context/pain-wiki/industries/<slug>.md`. 25 cards total.
  - **One lead magnet per industry.** It is no longer in the band: it rides on the plate as a
    leader-arrow annotation, "TAKE <MAGNET> TODAY", pointing at the painted subject.
  - Every card carries `q`, the number of the magnet question it walks the reader into.

    **`q` is NOT the card's position.** The playbook question order matches the ranked pain
    order in construction and real estate only. Hospitality, retail and financial services
    order their questions differently, and their magnets carry 8 questions against 5 or 6
    ranked pains, so financial services card 5 lands on question 6. Every `q` here was read off
    its playbook and checked by hand. Re-check it when a playbook's magnet changes.

## The band template (locked with you Every card sets exactly one sentence:

    AUSSIE <BUSINESS TYPE> ARE FINALLY REALISING THEY DON'T HAVE TO <PAIN> ANYMORE.

The accent is the pain clause. The CTA left the band for the plate, so the accent is free again.

**The "using AI" tail is cut.** you added it on and removed it the same day. Do not
put it back: the sentence lands on the pain, and naming the mechanism in the band answers a question
the card has not asked yet. What replaces the pain is the offer's job, not the hook's.

The business type is one plural per industry, in `WHO`. Construction is **construction businesses**,
never "builders": `context/language-rules.md` binds that and it is the audience sense of the word.

**The pain clause is a bucket, not a scene.** your call, against a first pass
that was too situation-specific. Name the pain the way the whole industry carries it, in the
fewest words that still land: "MANUALLY QUOTE", not "BURN WEEKS OF SOMEONE'S TIME ON A SINGLE
TENDER". The sentence describes the pain, never the action that produces it, and it is about
the business rather than a person inside it. Detail belongs in the dossier, not on the card.

Three tests before a clause ships. Would it read true for every business in the vertical, not
just the one that said it on the call. Does it name an outcome the owner already feels rather
than a task they perform. Does it fit the band in four or five lines. If a clause needs a
specific tool, a number or a time of day to make sense, it is a scene and it is too narrow.

Buckets repeat across sets on purpose: disconnected systems, admin by hand and the owner
bottleneck are the same pain in five verticals, and each set is read by its own audience. They
never repeat inside one set.

**The bucket rule is also why there are no figures on these cards.** The subject is plural and
industry-wide, so any number riding on it reads as an industry claim. Nearly every number in
the playbooks is one firm's ("$150,000 a year", "40 to 60 hours", "two hours", "ten o'clock",
"a thousand clients"). Section 3 of SKILL.md forbids widening those, and there is no room to
scope a figure to one business inside this sentence. The numbers stay in the dossier as the
evidence behind the bucket.

## Plates

`plate` is a slug in `plates-noir/` and the card reuses that deck's `slide-01`, the wordless
pain motif. `slide-01` only. Slides 2 to 6 of those decks are teach beats and solution wides,
so they argue the opposite of a pain card. Two pains had no plate on disk and get their own,
named `industry-<slug>` and generated by `build_industry.py`.

No plate repeats inside one industry's set of five. Plates DO repeat across sets (the owner
bottleneck motif carries four industries), which is deliberate: each set posts to its own
audience and the two never share a feed.
"""

# Each magnet is spec'd in full (title, questions, answer options) in its industry playbook.
# None of the five is built as a page yet; you has that in a separate session.
MAGNETS = {
    "construction-and-trades": "THE SITE-TO-PROFIT READINESS CHECK",
    "real-estate-and-property-management": "THE AI-READY AGENCY SCORE",
    "hospitality-and-food-service": "THE WOW FACTOR AUDIT",
    "retail-and-ecommerce": "THE RETAIL OPS AI READINESS CHECK",
    "financial-services-and-insurance": "THE BROKER AND ADVISER AI READINESS CHECK",
}

# Painted scenes for the two pains with no plate on disk. Style and light blocks come from
# decks_noir.py at render time, so these are the scene clause only.
NEW_PLATES = {
    "industry-tribal-knowledge": (
        "A vast dark machine hall where every control panel is blank and unlabelled, and the "
        "only lit thing in the frame is a small handwritten notebook held open against the "
        "chest of a lone faceless figure standing at the centre of it."),
    "industry-dormant-book": (
        "A cold archive of identical numbered client boxes on steel shelves receding far back "
        "into black, where only a small cluster of boxes near the front glows warm and worked "
        "while the rows behind them sit grey and untouched under a film of dust."),
}

# The plural the template opens on. One per industry. It must NAME THE VERTICAL, not gesture at
# it (you, : "hospitality venues" not "venues", "insurance brokers" not "brokers",
# "real estate agencies" not "agencies". A bare noun reads as the wrong industry to half the feed.
WHO = {
    "construction-and-trades": "AUSSIE CONSTRUCTION BUSINESSES",
    "real-estate-and-property-management": "AUSSIE REAL ESTATE AGENCIES",
    "hospitality-and-food-service": "AUSSIE HOSPITALITY VENUES",
    "retail-and-ecommerce": "AUSSIE RETAILERS",
    "financial-services-and-insurance": "AUSSIE INSURANCE BROKERS",
}

INDUSTRY_STATICS = [
    {
        "industry": "construction-and-trades",
        "cards": [
            # Playbook pain 1. Systems fragmentation, 59 calls, the heaviest in the pack.
            {"slug": "systems", "plate": "systems", "q": 1,
             "pain": "RUN ON DISCONNECTED SYSTEMS"},
            # Playbook pain 2. Double-handled admin, 35 calls.
            {"slug": "double-handling", "plate": "staff", "q": 2,
             "pain": "DOUBLE-HANDLE EVERY JOB"},
            # Playbook pain 3. Owner bottleneck, 35 calls.
            {"slug": "bottleneck", "plate": "bottleneck", "q": 3,
             "pain": "RUN EVERY DECISION THROUGH THE OWNER"},
            # Playbook pain 4. Quoting, 27 calls. The 40 to 60 hours is one builder's, so the
            # card says it qualitatively and the dossier carries the figure.
            {"slug": "quoting", "plate": "quoting", "q": 4,
             "pain": "MANUALLY QUOTE"},
            # Playbook pain 5. Growth without headcount, 23 calls.
            {"slug": "headcount", "plate": "headcount", "q": 5,
             "pain": "HIRE MORE ADMIN TO GROW"},
        ],
    },
    {
        "industry": "real-estate-and-property-management",
        "cards": [
            # Playbook pain 1. Admin-heavy, 24 of 27 calls.
            {"slug": "admin", "plate": "admin", "q": 1,
             "pain": "DROWN IN ADMIN"},
            # Playbook pain 2. Fragmented stack, 26 of 27 calls. The $150k is one agency's.
            {"slug": "systems", "plate": "governance", "q": 2,
             "pain": "RUN ON DISCONNECTED SYSTEMS"},
            # Playbook pain 3. Owner bottleneck, 13 of 27 calls.
            {"slug": "bottleneck", "plate": "bottleneck", "q": 3,
             "pain": "RUN EVERY DECISION THROUGH THE PRINCIPAL"},
            # Playbook pain 4. No real-time snapshot, 11 of 27 calls.
            {"slug": "numbers", "plate": "numbers", "q": 4,
             "pain": "GUESS AT THEIR OWN NUMBERS"},
            # Playbook pain 5. Listing and lead scarcity plus follow-up, 8 + 5 calls.
            {"slug": "leadgen", "plate": "leadgen", "q": 5,
             "pain": "LET LEADS GO COLD"},
        ],
    },
    {
        "industry": "hospitality-and-food-service",
        "cards": [
            # Playbook pain 1. Stale reporting, 20 of 23 calls, the biggest category.
            {"slug": "numbers", "plate": "numbers", "q": 1,
             "pain": "RUN ON LAST WEEK'S NUMBERS"},
            # Playbook pain 2. Staffing and no performance proof, 16 of 23 calls.
            {"slug": "hiring", "plate": "hiring", "q": 2,
             "pain": "HIRE ON GUT FEEL"},
            # Playbook pain 3. Admin that should run itself, 15 of 23 calls.
            {"slug": "admin", "plate": "inbox", "q": 4,
             "pain": "DO THE ADMIN BY HAND"},
            # Playbook pain 4. Tribal knowledge. No plate existed for this one.
            {"slug": "tribal-knowledge", "plate": "industry-tribal-knowledge", "q": 5,
             "pain": "KEEP THE PLAYBOOK IN ONE PERSON'S HEAD"},
            # Playbook pain 5. Nothing runs without the owner present, 11 of 23 calls.
            {"slug": "presence", "plate": "roster", "q": 3,
             "pain": "BE IN THE VENUE FOR IT TO RUN"},
        ],
    },
    {
        "industry": "retail-and-ecommerce",
        "cards": [
            # Playbook pain 1. Staff as the integration layer, 25 examples.
            {"slug": "systems", "plate": "systems", "q": 3,
             "pain": "RUN ON DISCONNECTED SYSTEMS"},
            # Playbook pain 2. Owner bottleneck, 14 owners.
            {"slug": "bottleneck", "plate": "bottleneck", "q": 2,
             "pain": "RUN EVERY DECISION THROUGH THE OWNER"},
            # Playbook pain 3. Stale reporting, 14 calls. The fourteenth is one owner's.
            {"slug": "numbers", "plate": "numbers", "q": 1,
             "pain": "RUN ON LAST MONTH'S NUMBERS"},
            # Playbook pain 4. Manual admin, 13 calls.
            {"slug": "admin", "plate": "staff", "q": 4,
             "pain": "DO THE ADMIN BY HAND"},
            # Playbook pain 5. Growth without headcount, 13 calls. The $10M to $17M is one
            # owner's, so the card says it qualitatively.
            {"slug": "headcount", "plate": "headcount", "q": 5,
             "pain": "HIRE MORE PEOPLE TO GROW"},
        ],
    },
    {
        "industry": "financial-services-and-insurance",
        "cards": [
            # Playbook pain 1. Context lost between people, 19 examples, 41% weight.
            # you, : reworded from "MAKE CLIENTS REPEAT THEMSELVES" to put the broker on
            # the acting side of the same failure. The playbook's own angle is "nobody in your
            # business ever asks a client to explain themselves twice", and magnet question 1 asks
            # what happens to what a client has already told you, so this is the pain as written.
            {"slug": "context", "plate": "cx", "q": 1,
             "pain": "KEEP ASKING CLIENTS THE SAME QUESTIONS"},
            # Playbook pain 2. Admin over advice, 10 examples. The 10 to 20 percent is one
            # broker's, so the card says it qualitatively.
            {"slug": "admin", "plate": "compliance", "q": 3,
             "pain": "DROWN IN PAPERWORK"},
            # Playbook pain 3. Owner personally building the automation, 7 examples.
            {"slug": "bottleneck", "plate": "bottleneck", "q": 4,
             "pain": "BUILD THE AUTOMATION THEMSELVES"},
            # Playbook pain 4. Dormant client book, 7 examples. The 1,000 and 600 are one
            # firm's, so the card says it qualitatively.
            {"slug": "dormant-book", "plate": "industry-dormant-book", "q": 5,
             "pain": "SIT ON A DORMANT CLIENT BOOK"},
            # Playbook pain 5. Vendor trust and data safety, 6 examples.
            {"slug": "trust", "plate": "security", "q": 6,
             "pain": "GUESS AT WHO THEY CAN TRUST"},
        ],
    },
]


def band_lines(industry, card):
    """The one sentence a card sets. The accent is the pain clause."""
    return [f"{WHO[industry]} ARE FINALLY REALISING THEY DON'T HAVE TO",
            f"[[{card['pain']}]] ANYMORE."]


def anno_label(industry):
    """The leader-arrow label that rides on the plate."""
    return f"TAKE {MAGNETS[industry]} TODAY"
